# Generated by Django 3.1.2 on 2022-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20221208_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.Teacher', verbose_name='Учителя'),
        ),
    ]
